### PR TITLE
Update void linux rootfs and wsldl to latest version

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Review by am11 — APPROVED** [review]
Thank you!
Would you be interested in applying the similar changes to https://git.io/voidmuslwsl?

**Comment by am11** [comment]
Available in release : [21030101](https://github.com/am11/VoidWSL/releases/tag/21030101)

**Comment by smorimoto** [comment]
Thanks!

**Comment by smorimoto** [comment]
> Would you be interested in applying the similar changes to https://git.io/voidmuslwsl?

Absolutely!

**Pull request merged**
