### PR TITLE
Consolidate musl build

### PR DESCRIPTION
**Pull request by tranzystorekk**
Notes:

- The zipballs are now `VoidGlibc.zip` and `VoidMusl.zip`
- Used canned makefile recipes to minimize code duplication

### CODE REVIEW

**Comment by am11** [comment]
Looks great. Thanks a lot @tranzystorek-io!

**Comment by tranzystorekk** [comment]
@am11 Noticed that now the launcher is always Void.exe, not sure if we want that...

**Comment by am11** [comment]
> Noticed that now the launcher is always Void.exe, not sure if we want that

I think this is alright. As long as zip files are separate (as before), wouldn't surprise the user.

**Comment by tranzystorekk** [comment]
hm, I'm not sure what happens if someone tries to install both variants at the same time, but probably the two launchers will conflict...

**Comment by am11** [comment]
Release created: https://github.com/am11/VoidWSL/releases/tag/22102201

>  but probably the two launchers will conflict...

They don't conflict, wsl creates different GUID for each registered instance.

**Comment by tranzystorekk** [comment]
Still might be a bit confusing to have two instances named "Void", if you don't mind, I have a quick fix for renaming the launchers almost ready 😄

**Comment by am11** [comment]
I don't mind cosmetic changes. Patches are welcome! :)

**Comment by am11** [comment]
Can use lowercase `void-glibc.exe` and `void-musl.exe`.

**Pull request merged**
