### PR TITLE
Bump Void revision to 20221001

### PR DESCRIPTION
**Pull request by tranzystorekk**

### CODE REVIEW

**Comment by am11** [comment]
Thanks. 👍
There is also https://github.com/am11/VoidMuslWSL.

**Comment by tranzystorekk** [comment]
Makes me wonder, that repo seems like a duplication of the whole package logic, maybe it could be merged into this one?

**Comment by am11** [comment]
Yep, I initially kept them separate as https://github.com/yuk7/wsldl consumers were using one OS per repo, and thought the setup of these two might get diverged over time, but it hasn't changed. We can abandon the other repo after merging them.

Would you like to give it a try? :)

**Comment by tranzystorekk** [comment]
> Would you like to give it a try? :)

Sure, I assume you'd prefer a separate PR?

**Comment by am11** [comment]
I will merge this PR and hold off the release until cosolidation is completed. Many thanks!

**Pull request merged**
